POST https://app-rgm-api.herokuapp.com/api/user/login
Content-Type: application/json

{
    "username": "admin",
    "password": 1234    
}

#################
GET  https://app-rgm-api.herokuapp.com/api/routes/user?origen=MLN&destination=BCN
Authorization: bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOjEyMzQsImlhdCI6MTYzNDExNjk1NX0.zKO_MFnxyIM3gnwe4F7wl_RnT_a3PEfNf-jVbhxN_Gg"


#################
GET  https://app-rgm-api.herokuapp.com/api/routes/list
Authorization: bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOjEyMzQsImlhdCI6MTYzNDExNjk1NX0.zKO_MFnxyIM3gnwe4F7wl_RnT_a3PEfNf-jVbhxN_Gg"

#################
GET  https://app-rgm-api.herokuapp.com/api/routes/remove
Authorization: bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOjEyMzQsImlhdCI6MTYzNDExNjk1NX0.zKO_MFnxyIM3gnwe4F7wl_RnT_a3PEfNf-jVbhxN_Gg"


#################
POST  https://app-rgm-api.herokuapp.com/api/user/signup
Content-Type: application/json

{
    "username": "user2",
    "password": 4567    
}

#################
GET  https://app-rgm-api.herokuapp.com/api/admin/list


################
DELETE https://app-rgm-api.herokuapp.com/api/admin/remove
Content-Type: application/json
Authorization: bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOjEyMzQsImlhdCI6MTYzNDExNjk1NX0.zKO_MFnxyIM3gnwe4F7wl_RnT_a3PEfNf-jVbhxN_Gg"

{
    "userId": 3,
    "username": "user2",
    "password": 4567    
}

#####################
GET https://app-rgm-api.herokuapp.com/api/airports


####################
GET https://app-rgm-api.herokuapp.com/api/routes?origen=MLN&destination=BCN


###################
GET https://app-rgm-api.herokuapp.com/api/airlines


###################
GET https://app-rgm-api.herokuapp.com/api/countries


####################
GET https://app-rgm-api.herokuapp.com/api/cities
